---
title: "Regression"
author: "IsaiahLG"
date: "4/19/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```


## Import Data
```{r}
# import necessary library
library(rdhs)

# set credentials for accessing DHS API
set_rdhs_config(email = "isaiah.lyons-galante@colorado.edu",
                project = "Machine Learning Class Project")

# download actual datasets
downloads <- get_datasets("SLHR7AFL.ZIP")

# read in the dataset
sl19 <- readRDS(downloads$SLHR7AFL)

# get the variable labels for all column headers
var_labels <- get_variable_labels(sl19)

# export data
saveRDS(sl19, "./data/sl19.rds")
```

## Cut Down Data 
```{r}
# read in RDS
sl19 <- readRDS("./data/sl19.rds")

# columns of interest
predictor <- "hv245" # Hectares of agricultural land (1 decimal)
target <- "hv271" # Wealth index factor score combined (5 decimals)
allCols <- c(predictor, target)

# filter
sl19two <- sl19[,allCols]


# export to RDS
saveRDS(sl19two, "./data/sl19two.rds")
```

## Clean Data
```{r}
# reimport
sl19two <- readRDS("./data/sl19two.rds")
df <- sl19two

# clean up data
df <- na.omit(df) # remove NA values
df <- haven::zap_labels(df) # remove labels
df <- df %>% mutate_at(allCols, as.numeric) # turn into numbers for filtering
df <- df %>% filter(hv245 < 950) # eliminate "unknown" answers and 950 high point
df <- df %>% filter(hv245 > 0) # eliminate 0s
df <- df %>% filter(hv271 > -146639) # eliminate outlier

# rename columns
colnames(df)[1] = "acres"
colnames(df)[2] = "wealth"

# export
sl19reg <- df
saveRDS(sl19reg, "./data/sl19reg.rds")
```

## Conduct Linear Regression
```{r}
# reread in object
sl19reg <- readRDS("./data/sl19reg.rds")
df <- sl19reg
y <- df$wealth
x <- df$acres

# examine histograms and boxplots
hist(x)
hist(y)
boxplot(x)
boxplot(y)
plot(x, y)

# linear regression attempt 1
model1 <- lm(y ~ x)
summary(model1)
plot(model1)

# shift all wealth values above 0
df$wealth0 <- y - min(y)
df$wealthsqrt <- (df$wealth0)^0.25
df$acreslog <- log(df$acres + 1)
x2 <- df$acreslog
y2 <- df$wealthsqrt

# rexamine histograms and boxplots
hist(x2)
hist(y2)
boxplot(x2)
boxplot(y2)
plot(x2, y2)
abline(lm(y2 ~ x2))


# linear regression attempt 2
model2 <- lm(y2 ~ x2)
summary(model2)
plot(model2)
```